'''
Task-1: Random Module

Pseudorandom Number Generators
Computers are not random, because they are built with circuits and switches. 
But randomness is very important when building software, especially games. 
It would be really boring if every move in a video game was pre-determined.

So, some computer scientists invented pseudorandom number generators. 
e.g. https://en.wikipedia.org/wiki/Mersenne_Twister

If you want to learn more about pseudorandom number generators, 
I recommend watching this video by Khan Academy: https://www.youtube.com/watch?v=GtOt7EBNEwQ&ab_channel=KhanAcademyLabs

The Random module in Python
Read the docs here: https://docs.python.org/3/library/random.html
To use it you need to first import it:
import random

Random Whole Numbers Within a Range
import random
rand_num = random.randint(1, 10)
#This will produce a random whole number between 1 and 10 (inclusive).

Modules in Python
Python allows us to put code into different files and import that code if needed. 
This means that we can better organise and modularise our code.
You can create a new module simply by creating a new .py file, and then you can import variables or functions from that file just by using the import keyword.

Random Floats
You can generate a random number between 0.0 (inclusive) and 1.0 (not inclusive) using the following code from the random module:
import random
rand_num_0_to_1 = random.random()

It can also be represented like this
0.0	<= random.random() < 1.0

You can expand the range of random numbers generated by this method using multiplication.
e.g. random.random() * 5
Will generate a random number between 0 and 5.

Another way to generate random floating point numbers is to use the uniform() function.

import random
random_float = random.uniform(1, 10)
#This will generate a random floating point number between 1 and 10. 

This method may or may not include the upper bound depending on the rounding of the floating point number. So it's best represented as:
a <= random.uniform(a,b) <= b

So depending on if you want the upper bound included you will choose whether to use random.random() or random.uniform().

PAUSE 1 - Heads or Tails
Create a coin flip program using what you have learnt about randomisation in Python. It should randomly print "Heads" or "Tails" everytime it is run.

Hint:
You'll need to think about what you have learnt about conditional statements in Python.
'''

import random
random_number = random.randint(1, 10)
print(random_number)

# import from other Python file
# my_module.py -> my_fav_number = 3.14
import my_module
print(my_module.my_fav_number)

random_number_0_to_1 = random.random() # number between 0 and 1 - 1 not included
random_number_0_to_10 = random.random() * 10 # number between 0 and 10 - 10 not included
print(random_number_0_to_1)
print(random_number_0_to_10)

random_float = random.uniform(1, 10)
print(random_float)

# heads or tails program
heads_or_tails = random.randint(0, 1)
if heads_or_tails == 0:
    print("Heads")
else:
    print("Tails")